services:
  postgres:
    container_name: postgres
    image: postgres:16.4
    ports:
      - 9000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dev-scripts/init-person-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: testcase
      POSTGRES_PASSWORD: postgres


volumes:
  postgres_data:
    external: false