# Configuration for setting up a Postgres database container in Docker to connect to it from a Kubernetes cluster.
name: person-api-dev

services:
  postgres:
    container_name: postgres-dev
    image: postgres:16.4
    ports:
      - 6000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dev-scripts/init-person-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: testcase
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data:
    external: false