# Configuration for setting up a Postgres database container in Docker to connect from the local environment.
name: person-api-local

services:
  postgres:
    container_name: postgres-local
    image: postgres:16.4
    ports:
      - 9001:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dev-scripts/init-person-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: testcase
      POSTGRES_PASSWORD: postgres


volumes:
  postgres_data:
    external: false