server:
  port: 8081

---
spring:
  docker:
    compose:
      enabled: true
      file: docker-compose-local.yml
      lifecycle-management: start-and-stop

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9000/testcase?currentSchema=person&useUnicode=true&characterEncoding=UTF8
    username: postgres
    password: postgres
