spring:
  application:
    name: person-api

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        default_schema: person
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    change-log: classpath:liquibase/master.yml
    default-schema: person
    enabled: true

  docker:
    compose:
      enabled: false

---
springdoc:
  swagger-ui:
    path: /person-api-documentation

---
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

  endpoint:
    health:
      show-details: "always"

#---
#logging:
#  level:
#    com:
#      testcase:
#        api:
#          persons: INFO


