# The LimitRange resource in Kubernetes applies to all Pods and containers within a specific namespace.
# It does not apply to nodes directly.
apiVersion: v1
kind: LimitRange
metadata:
  name: person-api-cpu-limit-range
  namespace: person-api-test
spec:
  limits:
    - default: # Sets the default CPU limit for containers to 100m (100 millicores)
        cpu: 100m
      defaultRequest: # Sets the default CPU request for containers to 100m (100 millicores)
        cpu: 100m
      max: # Sets the maximum allowed CPU limit for containers to 0.5 core
        cpu: 0.5
      min: # Sets the minimum allowed CPU limit for containers to 50m (50 millicores).
        cpu: 50m
      type: Container