apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: person-api-hpa
  namespace: person-api-test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: person-api-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
        - type: Percent
          value: 40
          periodSeconds: 15
        - type: Pods
          value: 1
          periodSeconds: 15
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
        - type: Percent
          value: 40
          periodSeconds: 15
        - type: Pods
          value: 1
          periodSeconds: 15
      selectPolicy: Min