openapi: 3.0.3
info:
  title: 'Person API'
  version: '0.1.0'
  description: |
    'This API allows retrieving persons. The Person API provides endpoints to interact with the person data stored in the system. 
    The API supports operations to retrieve detailed information about individual persons or a comprehensive list of all persons. 
    This can be useful for a variety of applications including user interfaces, reporting, data analysis, and integration with other systems.

    The API follows RESTful principles and is designed to be simple to use, yet powerful enough to handle complex use cases. 
    The data returned by the API includes extensive details about each person, such as their unique identifier, name, surname, date of birth, 
    address, country of origin, job title, etc. This level of detail ensures that the API can support a wide range of functionalities 
    and use cases, from simple lookups to comprehensive data processing tasks.

    The API is designed with flexibility and ease of integration in mind, allowing developers to easily incorporate person data into their applications. 
    Each endpoint is documented with comprehensive examples and descriptions to facilitate quick understanding and implementation.

    Common use cases for the Person API include:
    - Displaying person data in user interfaces, such as profile pages or contact lists
    - Populating dropdowns or selection fields with person data
    - Providing data for reporting and analytics
    - Integrating person data with other systems or services
    - Validating and processing person-related information'

tags:
  - name: Person
    description: 'Operations related to persons.'

paths:

  /persons:
    get:
      operationId: allPersons
      tags:
        - Person
      summary: 'Retrieve a list of all persons.'
      description: |
        'This endpoint returns a comprehensive list of all persons available in the database.
        The data can be used for various purposes such as displaying in a dropdown for user selection,
        providing data for reports, or populating person-specific information in your application.'
      parameters:
        - $ref: '#/components/parameters/personNameParam'
        - $ref: '#/components/parameters/personSurnameParam'
      responses:
        200:
          description: 'A list of persons.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PersonDto'
        400: # Bad Request
          description: 'Invalid request parameters.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 400
                message: 'Invalid request parameters.'
        401: # Unauthorized
          description: 'Authentication required.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 401
                message: 'Authentication required.'
        403: # Forbidden
          description: 'Insufficient permissions.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 403
                message: 'Insufficient permissions.'
        500: # Internal Server Error
          description: 'An unexpected error occurred.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 500
                message: 'An unexpected error occurred.'


  /persons/:
    post:
      operationId: createPerson
      tags:
        - Person
      summary: 'Create a new person'
      description: 'Endpoint to create a new person entry.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonMiniDto'
      responses:
        201:
          description: 'The person was created successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
        400: # Bad Request
          description: 'Invalid request parameters.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 400
                message: 'Invalid request parameters.'
        401: # Unauthorized
          description: 'Authentication required.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 401
                message: 'Authentication required.'
        403: # Forbidden
          description: 'Insufficient permissions.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 403
                message: 'Insufficient permissions.'
        500: # Internal Server Error
          description: 'An unexpected error occurred.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 500
                message: 'An unexpected error occurred.'


  /persons/{personIdParam}:
    get:
      operationId: onePerson
      tags:
        - Person
      summary: 'Retrieve a specific person by ID.'
      description: |
        'This endpoint returns detailed information about a specific person identified by their unique ID.
        This can be useful for obtaining person-specific data for display, processing, or integration with other systems.'
      parameters:
        - $ref: '#/components/parameters/personIdParam'
      responses:
        200:
          description: 'A single person.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
        400: # Bad Request
          description: 'Invalid request parameters.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 400
                message: 'Invalid request parameters.'
        401: # Unauthorized
          description: 'Authentication required.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 401
                message: 'Authentication required.'
        403: # Forbidden
          description: 'Insufficient permissions.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 403
                message: 'Insufficient permissions.'
        404: # Not Found
          description: 'Person not found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: 'Person not found'
        500: # Internal Server Error
          description: 'An unexpected error occurred.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 500
                message: 'An unexpected error occurred.'



    patch:
      operationId: updatePerson
      tags:
        - Person
      summary: 'Update a specific person by ID.'
      description: |
        'This endpoint allows updating the details of a person identified by their unique ID. 
        It is useful for modifying person-specific data such as name, address, or other attributes for display, processing, or integration with external systems.'
      parameters:
        - $ref: '#/components/parameters/personIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonMiniDto'
      responses:
        200:
          description: 'A single person.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
        400: # Bad Request
          description: 'Invalid request parameters.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 400
                message: 'Invalid request parameters.'
        401: # Unauthorized
          description: 'Authentication required.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 401
                message: 'Authentication required.'
        403: # Forbidden
          description: 'Insufficient permissions.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 403
                message: 'Insufficient permissions.'
        404: # Not Found
          description: 'Person not found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: 'Person not found.'
        500: # Internal Server Error
          description: 'An unexpected error occurred.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 500
                message: 'An unexpected error occurred.'

    delete:
      operationId: deletePerson
      tags:
        - Person
      summary: 'Delete a specific person by ID.'
      description: |
        'This endpoint allows you to delete a person identified by their unique ID. Once deleted, the person cannot be recovered.'
      parameters:
        - $ref: '#/components/parameters/personIdParam'
      responses:
        204: # No Content
          description: 'The person was successfully deleted. No content returned.'
        400: # Bad Request
          description: 'Invalid request parameters.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 400
                message: 'Invalid request parameters.'
        401: # Unauthorized
          description: 'Authentication required.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 401
                message: 'Authentication required.'
        403: # Forbidden
          description: 'Insufficient permissions.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 403
                message: 'Insufficient permissions.'
        404: # Not Found
          description: 'Person not found.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 404
                message: 'Person not found.'
        500: # Internal Server Error
          description: 'An unexpected error occurred.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: 500
                message: 'An unexpected error occurred.'


components:

  parameters:

    personIdParam:
      name: personIdParam
      in: path
      required: true
      description: 'The unique ID of the person whose details are being accessed or modified.'
      schema:
        type: string
        format: uuid

    personNameParam:
      name: personNameParam
      in: query
      description: 'The first name of the person, used to filter or search for specific records.'
      schema:
        type: string

    personSurnameParam:
      name: personSurnameParam
      in: query
      description: 'The last name of the person, used to filter or search for specific records.'
      schema:
        type: string


  schemas:

    PersonMiniDto:
      type: object
      required:
        - name
        - surname
        - dateOfBirth
        - address
        - country
        - jobTitle
      properties:
        name:
          type: string
          nullable: false
          description: 'The name of the person.'
          example: 'John'
        surname:
          type: string
          nullable: false
          description: 'The surname of the person.'
          example: 'Doe'
        dateOfBirth:
          type: string
          format: date
          nullable: false
          description: |
            'The date of birth of the person.
            Format: YYYY-MM-DD'
          example: '1990-01-01'
        address:
          type: string
          nullable: false
          description: 'The address of the person.'
          example: '123 Main St, Anytown, USA'
        country:
          $ref: '#/components/schemas/CountryCode'
        jobTitle:
          type: string
          nullable: false
          description: 'The job title of the person.'
          example: 'Software Engineer'
        annualSalary:
          type: number
          description: "A BigDecimal field representing an annual amount."
          example: 100000.00
        employer:
          type: string
        gender:
          $ref: '#/components/schemas/Gender'


    PersonDto:
      type: object
      required:
        - id
        - name
        - surname
        - dateOfBirth
        - address
        - country
        - jobTitle
      properties:
        id:
          type: string
          format: uuid
          description: 'The unique ID of the person.'
          example: '046b6c7f-0b8a-43b9-b35d-6489e6daee91'
        name:
          type: string
          nullable: false
          description: 'The name of the person.'
          example: 'John'
        surname:
          type: string
          nullable: false
          description: 'The surname of the person.'
          example: 'Doe'
        dateOfBirth:
          type: string
          format: date
          nullable: false
          description: |
            'The date of birth of the person.
            Format: YYYY-MM-DD'
          example: '1990-01-01'
        address:
          type: string
          nullable: false
          description: 'The address of the person.'
          example: '123 Main St, Anytown'
        country:
          $ref: '#/components/schemas/CountryCode'
        jobTitle:
          type: string
          nullable: false
          description: 'The job title of the person.'
          example: 'Software Engineer'
        annualSalary:
          type: number
          description: "A BigDecimal field representing an annual amount."
          example: 100000.00
        employer:
          type: string
          description: 'A person employer.'
          example: 'Abn-Amro'
        gender:
          $ref: '#/components/schemas/Gender'


    CountryCode:
      type: string
      x-enum-varnames:
        - US
        - DE
        - NL
        - CY
        - IT
        - UK
        - OTHER
      enum:
        - United States
        - Germany
        - Netherlands
        - Cyprus
        - Italy
        - United Kingdom
        - Other
      description: 'Enum representing a country where a person resides.'
      example: 'US'


    Gender:
      type: string
      enum:
        - MAN
        - WOMAN
        - NA
      description: 'Enum representing the gender of a person.'
      example: 'MAN'


    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          description: 'Error code.'
          example: 400
        message:
          type: string
          description: 'Error message.'
          example: 'Invalid request parameters.'