{{- if .Values.includePostgresChart }}
apiVersion: storage.k8s.io/v1
kind: StorageClass # A template for creating PersistentVolumes
metadata:
  name: {{ .Values.storageClass.metadata.name }}
provisioner: {{ .Values.storageClass.provisioner }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- end }}