apiVersion: v1
kind: Secret
metadata:
  name: {{ include "abnamro-person-api-chart.fullname" . }}-dockerhub-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.dockerConfigJson }}