apiVersion: v1
kind: ConfigMap
metadata:
  name: person-api-config-map
  namespace: person-api-test
data:
  SPRING_PROFILES_ACTIVE: "test"
  SERVER_PORT: "4001"
  init-db.sh: |
    #!/bin/bash
    # Wait for PostgreSQL to be ready
    until pg_isready -h localhost -p 5432; do
      echo "Waiting for PostgreSQL to start..."
      sleep 2
    done

    # Run the SQL command to create the schema
    psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "CREATE SCHEMA IF NOT EXISTS person;"