apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-api-deployment
  namespace: person-api-local
  labels:
    app: person-api-deployment
    function: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: person-api-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: person-api-deployment
        environment: local
        function: backend
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
        - name: person-api-container
          image: pavelbr368/persons:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: person-api-db-secrets
                  key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: person-api-db-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: person-api-db-secrets
                  key: DB_PASSWORD
          resources:
            requests:
              memory: 400Mi
              cpu: 0.2
            limits:
              memory: 600Mi
              cpu: 0.5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 8
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 8
#      progressDeadlineSeconds: 600