# Default values for abnamro-person-api-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# General
includePostgresChart: true
fullnameOverride: "abnamro-person-api" # metadata name
nameOverride: "abnamro-person-api"
labels: {}

# Kind: Deployment
deployment:
  replicaCount: 3

  image:
    repository: pavelbr368/abnamro-person-api
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: 0.1.5

  imagePullSecrets:
    - name: abnamro-person-api-dockerhub-registry

  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate

  resources:
    requests:
      memory: 400Mi
      cpu: 0.2
    limits:
      memory: 600Mi
      cpu: 0.5

  autoscaling:
    enabled: enable
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60

    # scaleDown
    scaleDownStabilizationWindowSeconds: 10
    scaleDownPercentValue: 40
    scaleDownPercentPeriodSeconds: 15
    scaleDownPodsValue: 1
    scaleDownPodsPeriodSeconds: 15
    scaleDownSelectPolicy: Max

    # scaleUp
    scaleUpStabilizationWindowSeconds: 10
    scaleUpPercentValue: 40
    scaleUpPercentPeriodSeconds: 15
    scaleUpPodsValue: 1
    scaleUpPodsPeriodSeconds: 15
    scaleUpSelectPolicy: Min

    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    securityContext: {}
    volumes: []
    volumeMounts: []
    nodeSelector: {}
    tolerations: []
    affinity: {}

# Kind: Registry
registry:
  dockerConfigJson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogImNHRjJaV3hpY2pNMk9EcGtZMnR5WDNCaGRGOWZjR2xUU0VkMVQzVk1VbU51ZDBGUlpYaENNV3RDTjFKWU4wMD0iCiAgICB9CiAgfQp9Cg==


# Kind: LimitRange
limitRange:
  default:
    cpu: 100m
    memory: 500Mi
  defaultRequest:
    cpu: 100m
    memory: 500Mi
  max:
    cpu: 0.5
    memory: 600Mi
  min:
    cpu: 50m
    memory: 400Mi
  type: Container


# Kind: HorizontalPodAutoscaler
hpa:
  autoscaling:
    minReplicas: 2
    maxReplicas: 5

# Kind: ConfigMap
configMap:
  data:
    springProfilesActive: test
    serverPort: 5001
    initDbSh: |