apiVersion: v1
kind: PersistentVolume
metadata:
  name: person-api-postgres-pv
  labels:
    type: person-api-test
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"