apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: person-api-test
  labels:
    app: postgres-service
spec:
  type: LoadBalancer
  selector:
    app: postgres-deployment
  ports:
    - name: postgres-http
      port: 15000
      targetPort: 5432